apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nobl9-project-template
  title: Create Nobl9 Project
  description: Create a new Nobl9 project with user role assignments
  tags:
    - nobl9
    - project
    - sre
    - monitoring
spec:
  owner: nobl9-team
  type: template
  
  parameters:
    - title: Project Information
      required:
        - projectName
        - displayName
        - appid
        - ba_number
      properties:
        projectName:
          title: Project Name
          type: string
          description: Unique name for the Nobl9 project
          pattern: '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'
          minLength: 1
          maxLength: 63
          ui:autofocus: true
          ui:field: TextField
          ui:options:
            rows: 1
            placeholder: "my-project-name"
        displayName:
          title: Display Name
          type: string
          description: Human-readable name for the project
          minLength: 1
          maxLength: 63
          ui:field: TextField
          ui:options:
            rows: 1
            placeholder: "My Project Name"
        appid:
          title: Application ID
          type: string
          description: Application identifier for the project
          minLength: 1
          maxLength: 50
          ui:field: TextField
          ui:options:
            rows: 1
            placeholder: "ctx"
        ba_number:
          title: BA Number
          type: string
          description: Business Application number
          pattern: '^BA[0-9]{7}$'
          minLength: 9
          maxLength: 9
          ui:field: TextField
          ui:options:
            rows: 1
            placeholder: "BA0008972"
        description:
          title: Description
          type: string
          description: Optional description of the project
          ui:field: TextField
          ui:options:
            rows: 3
            placeholder: "Describe the purpose of this project..."

    - title: User Management
      required:
        - users
      properties:
        users:
          title: Project Users
          type: array
          description: Add users and assign roles to this project
          items:
            type: object
            required:
              - email
              - role
            properties:
              email:
                title: Email Address
                type: string
                description: User's email address
                format: email
                ui:field: TextField
                ui:options:
                  rows: 1
                  placeholder: "user@company.com"
              role:
                title: Role
                type: string
                description: User's role in the project
                enum:
                  - project-owner
                  - project-editor
                default: project-editor
                ui:field: Select
                ui:options:
                  enumOptions:
                    - value: project-owner
                      label: Project Owner (Full Access)
                    - value: project-editor
                      label: Project Editor (Manage SLOs & Services)
          ui:options:
            orderable: false
            addable: true
            removable: true
            minItems: 1
            addButtonText: "+ Add User"
            removeButtonText: "Remove User"

  steps:
    - id: debug-params
      name: Debug Parameters
      action: debug:log
      input:
        message: |
          Parameters received:
          - projectName: ${{ parameters.projectName }}
          - displayName: ${{ parameters.displayName }}
          - appid: ${{ parameters.appid }}
          - ba_number: ${{ parameters.ba_number }}
          - description: ${{ parameters.description }}
          - users: ${{ parameters.users | toJson }}

    - id: trigger-github-action
      name: Trigger Nobl9 GitHub Action
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=dfaile&repo=Nobl9-github-action
        workflowId: nobl9-project-sync.yml
        branchOrTagName: main
        workflowInputs:
          project_name: ${{ parameters.projectName }}
          display_name: ${{ parameters.displayName }}
          app_id: ${{ parameters.appid }}
          ba_number: ${{ parameters.ba_number }}
          description: ${{ parameters.description }}
          users: ${{ parameters.users | toJson }}

  output:
    links:
      - title: GitHub Actions
        url: https://github.com/dfaile/Nobl9-github-action/actions
      - title: Repository
        url: https://github.com/dfaile/Nobl9-github-action
    text:
      - title: ✅ Success!
        content: |
          Your Nobl9 project workflow has been triggered successfully!
          
          **Project Details:**
          - **Project Name:** `${{ parameters.projectName }}`
          - **Display Name:** ${{ parameters.displayName }}
          - **App ID:** ${{ parameters.appid }}
          - **BA Number:** ${{ parameters.ba_number }}
          - **Users:** {{ parameters.users | length }} users assigned
          
          **Repository:** https://github.com/dfaile/Nobl9-github-action
          
      - title: 🚀 What Happens Next
        content: |
          The GitHub Action will process the parameters and create the project in Nobl9.
          
          **Monitor Progress:**
          - Check the GitHub Actions tab in the repository
          - Look for "Nobl9 Project Sync" workflow runs
          - Review logs for detailed deployment information
